import { useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { CheckCircle2, GitBranch, Pencil, Plus, Trash2 } from 'lucide-react'
import { z } from 'zod'
import { ConfirmDialog } from '../../components/ConfirmDialog'
import { ExportButtons } from '../../components/ExportButtons'
import { EmptyState, Panel } from '../../components/Panel'
import { useRecords } from '../../hooks/useRecords'
import { makeId, timestamp } from '../../lib/db'
import { normalizePriorities } from '../../lib/priority'
import type { EmpathyMap, RequirementMapping, RoperDynagram } from '../../types/research'

const schema = z.object({
  insightId: z.string(), segmentId: z.string(), functionalRequirement: z.string().min(8, 'Describe el requisito funcional.'), uxRequirement: z.string().min(8, 'Describe el requisito UX o no funcional.'), basePriority: z.coerce.number().min(1).max(10), impactFactor: z.coerce.number().min(0.1).max(10), validationStatus: z.enum(['pendiente', 'validado', 'requiere seguimiento']), architectureDecision: z.string().min(8, 'Registra una decisión de arquitectura.'),
}).refine((data) => Boolean(data.insightId || data.segmentId), { message: 'Vincula al menos un insight o un segmento.', path: ['insightId'] })
type FormValues = z.infer<typeof schema>
const empty = (): FormValues => ({ insightId: '', segmentId: '', functionalRequirement: '', uxRequirement: '', basePriority: 5, impactFactor: 1, validationStatus: 'pendiente', architectureDecision: '' })

export function RequirementsView() {
  const mappings = useRecords<RequirementMapping>('requirements')
  const empathy = useRecords<EmpathyMap>('empathyMaps')
  const roper = useRecords<RoperDynagram>('roperDynagrams')
  const activeRoper = roper.records[0]
  const [editing, setEditing] = useState<RequirementMapping | null>(null)
  const [selectedId, setSelectedId] = useState<string>('')
  const [pendingDelete, setPendingDelete] = useState<RequirementMapping | null>(null)
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: empty() })
  const insights = useMemo(() => empathy.records.flatMap((map) => map.insights.map((insight) => ({ ...insight, mapSubject: map.subject }))), [empathy.records])
  useEffect(() => { form.reset(editing ? { insightId: editing.insightId ?? '', segmentId: editing.segmentId ?? '', functionalRequirement: editing.functionalRequirement, uxRequirement: editing.uxRequirement, basePriority: editing.basePriority, impactFactor: editing.impactFactor, validationStatus: editing.validationStatus, architectureDecision: editing.architectureDecision } : empty()) }, [editing, form])
  useEffect(() => {
    const normalized = normalizePriorities(mappings.records, activeRoper)
    if (normalized.some((record, index) => record.computedPriority !== mappings.records[index]?.computedPriority)) void Promise.all(normalized.map((record) => mappings.upsert(record)))
  }, [activeRoper, mappings])
  const submit = async (values: FormValues) => {
    const insight = insights.find((item) => item.id === values.insightId)
    const segment = activeRoper?.segments.find((item) => item.id === values.segmentId)
    const draft: RequirementMapping = { id: editing?.id ?? makeId('requirement'), createdAt: editing?.createdAt ?? timestamp(), updatedAt: timestamp(), insightId: values.insightId || undefined, insightLabel: insight ? `${insight.description} (${insight.mapSubject})` : 'Sin insight enlazado', segmentId: values.segmentId || undefined, segmentLabel: segment?.name ?? 'Sin segmento enlazado', functionalRequirement: values.functionalRequirement, uxRequirement: values.uxRequirement, basePriority: values.basePriority, impactFactor: values.impactFactor, computedPriority: 0, validationStatus: values.validationStatus, architectureDecision: values.architectureDecision }
    const other = mappings.records.filter((item) => item.id !== draft.id)
    const normalized = normalizePriorities([...other, draft], activeRoper)
    await Promise.all(normalized.map((item) => mappings.upsert(item)))
    setEditing(null); setSelectedId(draft.id)
  }
  const selected = mappings.records.find((item) => item.id === selectedId) ?? mappings.records[0]
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Método 6 · crítico</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Mapeo de requerimientos</h1><p className="mt-2 max-w-3xl text-slate-600">Conecta hallazgos de Needfinding/Empathy y segmentos Roper con decisiones de producto y arquitectura.</p></header>
    <div className="rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-950"><div className="flex gap-3"><GitBranch className="shrink-0 text-teal-700" aria-hidden="true" /><div><strong>Ley embebida activa.</strong> Al guardar un cambio de prioridad base, factor de impacto o al modificar asignaciones Roper, se recalcula el porcentaje de todos los requisitos relacionados. Fórmula: <code className="rounded bg-white px-1">(base × factor × cuota del segmento) / Σ(base × factor × cuota) × 100</code>. La fórmula está documentada en <code>src/lib/priority.ts</code>.</div></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><Panel title={editing ? 'Editar requisito enlazado' : 'Nuevo requisito enlazado'} subtitle="Las fuentes se leen en vivo desde los métodos 4 y 5."><form className="space-y-4" onSubmit={form.handleSubmit(submit)} noValidate><div className="grid gap-4 md:grid-cols-2"><Field label="Insight de Empathy Map"><select className="field" {...form.register('insightId')}><option value="">Sin insight</option>{insights.map((insight) => <option value={insight.id} key={insight.id}>{insight.description.slice(0, 80)}{insight.description.length > 80 ? '…' : ''}</option>)}</select></Field><Field label="Segmento de Roper"><select className="field" {...form.register('segmentId')}><option value="">Sin segmento</option>{activeRoper?.segments.map((segment) => <option value={segment.id} key={segment.id}>{segment.name}</option>)}</select></Field></div>{form.formState.errors.insightId?.message && <p className="error">{form.formState.errors.insightId.message}</p>}<Field label="Requisito funcional *" error={form.formState.errors.functionalRequirement?.message}><textarea className="field min-h-20" placeholder="Qué debe hacer el sistema" {...form.register('functionalRequirement')} /></Field><Field label="Requisito UX / no funcional *" error={form.formState.errors.uxRequirement?.message}><textarea className="field min-h-20" placeholder="Calidad de interacción, accesibilidad o desempeño" {...form.register('uxRequirement')} /></Field><div className="grid gap-4 md:grid-cols-3"><Field label="Prioridad base (1-10) *" error={form.formState.errors.basePriority?.message}><input type="number" min="1" max="10" className="field" {...form.register('basePriority', { valueAsNumber: true })} /></Field><Field label="Factor impacto (0.1-10) *" error={form.formState.errors.impactFactor?.message}><input type="number" min="0.1" max="10" step="0.1" className="field" {...form.register('impactFactor', { valueAsNumber: true })} /></Field><Field label="Validación con usuario *"><select className="field" {...form.register('validationStatus')}><option value="pendiente">Pendiente</option><option value="validado">Validado</option><option value="requiere seguimiento">Requiere seguimiento</option></select></Field></div><Field label="Decisión de arquitectura *" error={form.formState.errors.architectureDecision?.message}><textarea className="field min-h-20" placeholder="Componente, patrón o restricción técnica que materializa el requisito" {...form.register('architectureDecision')} /></Field><div className="flex flex-wrap gap-3"><button className="btn-primary"><Plus size={16} /> {editing ? 'Recalcular y guardar' : 'Crear y calcular'}</button>{editing && <button type="button" className="btn-secondary" onClick={() => setEditing(null)}>Cancelar edición</button>}</div></form></Panel>
      <Panel title="Backlog normalizado" subtitle={`${mappings.records.length} requisito(s); la prioridad relativa se mantiene en 100%.`} actions={<ExportButtons label="moderai-mapeo-requerimientos" records={mappings.records as unknown as Record<string, unknown>[]} />}><div className="space-y-3">{mappings.loading ? <p className="text-sm text-slate-500">Cargando…</p> : mappings.records.length === 0 ? <EmptyState>Enlaza un insight o segmento para crear el primer requisito.</EmptyState> : [...mappings.records].sort((a, b) => b.computedPriority - a.computedPriority).map((mapping) => <article className={`rounded-xl border p-4 ${selected?.id === mapping.id ? 'border-teal-600 bg-teal-50' : 'border-slate-200'}`} key={mapping.id}><button className="w-full text-left" onClick={() => setSelectedId(mapping.id)}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><span className="tag">{mapping.segmentLabel}</span><span className="tag bg-slate-100 !text-slate-700">{mapping.validationStatus}</span></div><strong className="text-lg text-teal-800">{mapping.computedPriority}%</strong></div><p className="mt-2 font-semibold text-slate-900">{mapping.functionalRequirement}</p><p className="mt-1 text-sm text-slate-600">{mapping.insightLabel}</p></button><div className="mt-3 flex gap-2"><button className="btn-secondary !px-2 !py-1" onClick={() => setEditing(mapping)}><Pencil size={14} /> Editar</button><button className="btn-secondary !px-2 !py-1 text-rose-700" onClick={() => setPendingDelete(mapping)}><Trash2 size={14} /> Eliminar</button></div></article>)}</div></Panel></div>
    <Panel title="Vista de trazabilidad navegable" subtitle="Selecciona un requisito del árbol o backlog para inspeccionar su relación insight → requisito → arquitectura.">{selected ? <div className="overflow-x-auto"><div className="min-w-[760px] py-4"><div className="grid grid-cols-[1fr_80px_1fr_80px_1fr] items-center gap-3"><TraceNode label="Insight / evidencia" body={selected.insightLabel} accent="border-violet-500" /><Arrow /><button className="rounded-xl border-2 border-teal-600 bg-teal-50 p-4 text-left shadow-sm hover:bg-teal-100" onClick={() => setEditing(selected)}><p className="text-xs font-bold uppercase tracking-wider text-teal-800">Requisito</p><p className="mt-2 font-semibold text-slate-900">{selected.functionalRequirement}</p><p className="mt-2 text-xs text-slate-600">UX: {selected.uxRequirement}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-teal-800"><CheckCircle2 size={14} /> {selected.computedPriority}% · {selected.validationStatus}</span></button><Arrow /><TraceNode label="Decisión de arquitectura" body={selected.architectureDecision} accent="border-amber-500" /></div><p className="mt-4 text-center text-xs text-slate-500">Segmento asociado: {selected.segmentLabel}. Usa el requisito central para editar sus vínculos.</p></div></div> : <EmptyState>Selecciona o crea un requisito para dibujar la trazabilidad.</EmptyState>}</Panel>
    <ConfirmDialog open={Boolean(pendingDelete)} message="Se eliminará el requisito. Las prioridades restantes se normalizarán de nuevo." onCancel={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) void mappings.destroy(pendingDelete.id); if (selectedId === pendingDelete?.id) setSelectedId(''); if (editing?.id === pendingDelete?.id) setEditing(null); setPendingDelete(null) }} />
  </div>
}
function Arrow() { return <div className="flex items-center justify-center text-3xl font-black text-teal-700" aria-hidden="true">→</div> }
function TraceNode({ label, body, accent }: { label: string; body: string; accent: string }) { return <article className={`rounded-xl border-2 bg-white p-4 shadow-sm ${accent}`}><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold text-slate-800">{body}</p></article> }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="label">{label}{children}{error && <span className="error">{error}</span>}</label> }
