import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Pencil, Trash2 } from 'lucide-react'
import { z } from 'zod'
import { ConfirmDialog } from '../../components/ConfirmDialog'
import { ExportButtons } from '../../components/ExportButtons'
import { EmptyState, Panel } from '../../components/Panel'
import { useRecords } from '../../hooks/useRecords'
import { makeId, timestamp } from '../../lib/db'
import type { Observation } from '../../types/research'

const schema = z.object({ place: z.string().min(2, 'Indica el lugar o entorno.'), date: z.string().min(1, 'Selecciona una fecha.'), duration: z.string().min(2, 'Indica la duración.'), activity: z.string().min(3, 'Describe la actividad.'), obviousNeeds: z.string().min(5, 'Registra necesidades de superficie.'), hiddenNeeds: z.string().min(5, 'Registra necesidades profundas.'), rawBehavior: z.string().min(8, 'Describe solo lo observado.'), interpretation: z.string().min(8, 'Agrega una inferencia razonada.'), innovationPotential: z.enum(['bajo', 'alto']) })
type FormValues = z.infer<typeof schema>
const empty = (): FormValues => ({ place: '', date: '', duration: '', activity: '', obviousNeeds: '', hiddenNeeds: '', rawBehavior: '', interpretation: '', innovationPotential: 'alto' })

export function NeedfindingView() {
  const { records, loading, upsert, destroy } = useRecords<Observation>('observations')
  const [editing, setEditing] = useState<Observation | null>(null)
  const [pendingDelete, setPendingDelete] = useState<Observation | null>(null)
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: empty() })
  useEffect(() => { form.reset(editing ?? empty()) }, [editing, form])
  const submit = async (values: FormValues) => { await upsert({ ...values, id: editing?.id ?? makeId('observation'), createdAt: editing?.createdAt ?? timestamp(), updatedAt: timestamp() }); setEditing(null) }
  const error = (key: keyof FormValues) => form.formState.errors[key]?.message as string | undefined
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Método 3</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Needfinding · El Iceberg</h1><p className="mt-2 max-w-3xl text-slate-600">Separa con disciplina lo que ocurrió de lo que interpretas, y contrasta necesidades expresas con las que están bajo la superficie.</p></header>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Panel title={editing ? 'Editar observación' : 'Nueva observación'} subtitle="Dato crudo ≠ interpretación. Esa separación hace auditables tus hallazgos."><form className="space-y-4" onSubmit={form.handleSubmit(submit)} noValidate><div className="grid gap-4 sm:grid-cols-2"><Field label="Lugar / contexto *" error={error('place')}><input className="field" {...form.register('place')} /></Field><Field label="Fecha *" error={error('date')}><input type="date" className="field" {...form.register('date')} /></Field><Field label="Duración *" error={error('duration')}><input className="field" placeholder="p. ej., 30 min" {...form.register('duration')} /></Field><Field label="Actividad observada *" error={error('activity')}><input className="field" {...form.register('activity')} /></Field></div><div className="grid gap-4 md:grid-cols-2"><Field label="Necesidades obvias · superficie *" hint="Lo que solicita explícitamente"><textarea className="field min-h-28" {...form.register('obviousNeeds')} /></Field><Field label="Necesidades ocultas · profundidad *" hint="Emociones, motivaciones, frustraciones silenciadas"><textarea className="field min-h-28" {...form.register('hiddenNeeds')} /></Field></div><div className="grid gap-4 md:grid-cols-2"><Field label="Dato crudo observado *" hint="Comportamientos visibles, sin explicar por qué" error={error('rawBehavior')}><textarea className="field min-h-28" {...form.register('rawBehavior')} /></Field><Field label="Interpretación / inferencia *" hint="Hipótesis que puedes validar después" error={error('interpretation')}><textarea className="field min-h-28" {...form.register('interpretation')} /></Field></div><Field label="Potencial de innovación *" error={error('innovationPotential')}><select className="field max-w-xs" {...form.register('innovationPotential')}><option value="alto">Alto</option><option value="bajo">Bajo</option></select></Field><div className="flex flex-wrap gap-3"><button className="btn-primary">{editing ? 'Guardar cambios' : 'Guardar observación'}</button>{editing && <button type="button" className="btn-secondary" onClick={() => setEditing(null)}>Cancelar edición</button>}</div></form></Panel>
      <Panel title="Bitácora" subtitle={`${records.length} observación(es) guardada(s)`} actions={<ExportButtons label="moderai-needfinding" records={records as unknown as Record<string, unknown>[]} />}><div className="space-y-3">{loading ? <p className="text-sm text-slate-500">Cargando…</p> : records.length === 0 ? <EmptyState>Registra una observación de campo para iniciar el iceberg.</EmptyState> : records.map((record) => <article className="rounded-xl border border-slate-200 p-4" key={record.id}><div className="flex justify-between gap-2"><div><div className="flex gap-2"><h3 className="font-bold text-slate-900">{record.activity}</h3><span className={record.innovationPotential === 'alto' ? 'tag bg-amber-50 !text-amber-800' : 'tag'}>{record.innovationPotential}</span></div><p className="mt-1 text-sm text-slate-600">{record.place} · {record.date} · {record.duration}</p></div><div className="flex gap-1"><button className="btn-secondary !p-2" onClick={() => setEditing(record)} aria-label="Editar observación"><Pencil size={16} /></button><button className="btn-secondary !p-2 text-rose-700" onClick={() => setPendingDelete(record)} aria-label="Eliminar observación"><Trash2 size={16} /></button></div></div><p className="mt-3 border-l-4 border-teal-500 pl-3 text-sm text-slate-700"><strong>Profundidad:</strong> {record.hiddenNeeds}</p><p className="mt-2 text-sm text-slate-600"><strong>Crudo:</strong> {record.rawBehavior}</p></article>)}</div></Panel></div>
    <ConfirmDialog open={Boolean(pendingDelete)} message="Se eliminará esta observación y sus capas de iceberg." onCancel={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) void destroy(pendingDelete.id); setPendingDelete(null); if (editing?.id === pendingDelete?.id) setEditing(null) }} />
  </div>
}
function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: React.ReactNode }) { return <label className="label">{label}{children}{hint && <span className="help">{hint}</span>}{error && <span className="error">{error}</span>}</label> }
