import { useEffect, useMemo, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Pie, PieChart, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { z } from 'zod'
import { ConfirmDialog } from '../../components/ConfirmDialog'
import { ExportButtons } from '../../components/ExportButtons'
import { EmptyState, Panel } from '../../components/Panel'
import { useRecords } from '../../hooks/useRecords'
import { makeId, timestamp } from '../../lib/db'
import type { RoperDynagram, Segment, SegmentAssignment } from '../../types/research'

const configSchema = z.object({ title: z.string().min(3, 'Da un nombre a esta segmentación.') })
const segmentSchema = z.object({ name: z.string().min(2, 'Nombre requerido.'), values: z.string().min(3, 'Agrega valores asociados.'), uxRequirement: z.string().min(5, 'Define un requisito UX.'), keyFeature: z.string().min(5, 'Indica funcionalidad clave.'), systemTone: z.string().min(3, 'Indica el tono.') })
const assignmentSchema = z.object({ userId: z.string().min(1, 'Selecciona un participante.'), segmentIds: z.array(z.string()).min(1, 'Asigna al menos un segmento.'), evidence: z.string().min(5, 'Agrega evidencia de la asignación.') })
type ConfigForm = z.infer<typeof configSchema>; type SegmentForm = z.infer<typeof segmentSchema>; type AssignmentForm = z.infer<typeof assignmentSchema>
const colors = ['#0f766e', '#2563eb', '#d97706', '#9333ea', '#e11d48', '#0891b2']

export function RoperView() {
  const roperRecords = useRecords<RoperDynagram>('roperDynagrams')
  const users = useRecords<{ id: string; alias: string; createdAt: string; updatedAt: string }>('extremeUsers')
  const { records, loading, upsert, destroy } = roperRecords
  const [active, setActive] = useState<RoperDynagram | null>(null)
  const selectedInitialConfig = useRef(false)
  const [activeSegmentId, setActiveSegmentId] = useState<string>('')
  const [editingSegment, setEditingSegment] = useState<Segment | null>(null)
  const [editingAssignment, setEditingAssignment] = useState<SegmentAssignment | null>(null)
  const [pendingDelete, setPendingDelete] = useState<RoperDynagram | null>(null)
  const configForm = useForm<ConfigForm>({ resolver: zodResolver(configSchema), defaultValues: { title: '' } })
  const segmentForm = useForm<SegmentForm>({ resolver: zodResolver(segmentSchema), defaultValues: { name: '', values: '', uxRequirement: '', keyFeature: '', systemTone: '' } })
  const assignmentForm = useForm<AssignmentForm>({ resolver: zodResolver(assignmentSchema), defaultValues: { userId: '', segmentIds: [], evidence: '' } })
  useEffect(() => { if (!selectedInitialConfig.current && records.length > 0) { selectedInitialConfig.current = true; setActive(records[0]) } }, [records])
  useEffect(() => { configForm.reset({ title: active?.title ?? '' }); setActiveSegmentId(active?.segments[0]?.id ?? '') }, [active, configForm])
  useEffect(() => { segmentForm.reset(editingSegment ?? { name: '', values: '', uxRequirement: '', keyFeature: '', systemTone: '' }) }, [editingSegment, segmentForm])
  useEffect(() => { assignmentForm.reset(editingAssignment ? { userId: editingAssignment.userId ?? '', segmentIds: editingAssignment.segmentIds, evidence: editingAssignment.evidence } : { userId: '', segmentIds: [], evidence: '' }) }, [editingAssignment, assignmentForm])
  const saveConfig = async (values: ConfigForm) => { const saved = await upsert({ id: active?.id ?? makeId('roper'), createdAt: active?.createdAt ?? timestamp(), updatedAt: timestamp(), title: values.title, segments: active?.segments ?? [], assignments: active?.assignments ?? [] }); setActive(saved) }
  const update = async (patch: Partial<RoperDynagram>) => { if (!active) return; const saved = await upsert({ ...active, ...patch, updatedAt: timestamp() }); setActive(saved) }
  const saveSegment = async (values: SegmentForm) => { if (!active) return; const segment: Segment = { id: editingSegment?.id ?? makeId('segment'), ...values }; const segments = editingSegment ? active.segments.map((item) => item.id === segment.id ? segment : item) : [...active.segments, segment]; await update({ segments }); setEditingSegment(null); setActiveSegmentId(segment.id) }
  const deleteSegment = async (id: string) => { if (!active) return; await update({ segments: active.segments.filter((item) => item.id !== id), assignments: active.assignments.map((item) => ({ ...item, segmentIds: item.segmentIds.filter((segmentId) => segmentId !== id) })).filter((item) => item.segmentIds.length > 0) }); if (activeSegmentId === id) setActiveSegmentId('') }
  const saveAssignment = async (values: AssignmentForm) => { if (!active) return; const participant = users.records.find((item) => item.id === values.userId); if (!participant) return; const assignment: SegmentAssignment = { id: editingAssignment?.id ?? makeId('assignment'), userId: participant.id, alias: participant.alias, segmentIds: values.segmentIds, evidence: values.evidence }; const assignments = editingAssignment ? active.assignments.map((item) => item.id === assignment.id ? assignment : item) : [...active.assignments, assignment]; await update({ assignments }); setEditingAssignment(null) }
  const deleteAssignment = async (id: string) => { if (active) await update({ assignments: active.assignments.filter((item) => item.id !== id) }) }
  const validAssignments = useMemo(() => active?.assignments.filter((assignment) => !assignment.userId || users.records.some((user) => user.id === assignment.userId)) ?? [], [active, users.records])
  const chartData = useMemo(() => active?.segments.map((segment) => { const count = validAssignments.filter((assignment) => assignment.segmentIds.includes(segment.id)).length; const total = active.segments.reduce((sum, s) => sum + validAssignments.filter((assignment) => assignment.segmentIds.includes(s.id)).length, 0) || 1; return { id: segment.id, name: segment.name, count, quota: Math.round((count / total) * 1000) / 10 } }) ?? [], [active, validAssignments])
  const selectedSegment = active?.segments.find((segment) => segment.id === activeSegmentId) ?? active?.segments[0]
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Método 5</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Roper Dynagram</h1><p className="mt-2 max-w-3xl text-slate-600">Segmenta por valores, asigna evidencia por participante y observa cómo la rueda se recalcula al cambiar cualquier asignación.</p></header>
    <div className="grid gap-6 xl:grid-cols-[.68fr_1.32fr]"><Panel title={active ? 'Segmentación seleccionada' : 'Crear segmentación'} subtitle="Puedes tener más de una configuración de Roper."><form className="space-y-3" onSubmit={configForm.handleSubmit(saveConfig)} noValidate><Field label="Nombre de la segmentación *" error={configForm.formState.errors.title?.message}><input className="field" placeholder="p. ej., Muestra abril" {...configForm.register('title')} /></Field><button className="btn-primary">{active ? 'Guardar nombre' : 'Crear Dynagram'}</button>{active && <button type="button" className="btn-secondary ml-2" onClick={() => setActive(null)}>Nuevo</button>}</form><div className="mt-6 border-t border-slate-200 pt-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">Configuraciones</h3><ExportButtons label="moderai-roper-dynagram" records={records as unknown as Record<string, unknown>[]} /></div>{loading ? <p className="text-sm text-slate-500">Cargando…</p> : records.length === 0 ? <EmptyState>Crea una segmentación para comenzar.</EmptyState> : <div className="space-y-2">{records.map((record) => <div key={record.id} className={`rounded-lg border p-3 ${active?.id === record.id ? 'border-teal-600 bg-teal-50' : 'border-slate-200'}`}><button className="w-full text-left" onClick={() => setActive(record)}><strong className="block text-sm">{record.title}</strong><span className="text-xs text-slate-600">{record.segments.length} segmentos · {record.assignments.length} asignaciones</span></button><button className="btn-secondary mt-2 !px-2 !py-1 text-rose-700" onClick={() => setPendingDelete(record)}><Trash2 size={14} /> Eliminar</button></div>)}</div>}</div></Panel>
      {active ? <div className="space-y-6"><Panel title="Rueda de segmentos" subtitle="Cuota = membresías observadas ÷ total de membresías observadas. Se actualiza sin recargar."><div className="grid gap-4 lg:grid-cols-[1fr_.75fr]"><div className="h-80" aria-label="Gráfico polar de segmentos"><ResponsiveContainer><PieChart><Pie data={chartData} dataKey="count" nameKey="name" cx="50%" cy="50%" outerRadius={112} minAngle={4} onClick={(data) => setActiveSegmentId(data.id)}>{chartData.map((item, index) => <Cell key={item.id} fill={colors[index % colors.length]} stroke={item.id === selectedSegment?.id ? '#0f172a' : '#fff'} strokeWidth={item.id === selectedSegment?.id ? 3 : 1} />)}</Pie><Tooltip formatter={(value, _name, context) => [`${context.payload.quota}% · ${value} asignación(es)`, 'Cuota']} /><Legend /></PieChart></ResponsiveContainer></div><aside className="rounded-xl bg-mist p-4"><p className="text-xs font-bold uppercase tracking-wide text-teal-800">Panel dinámico</p>{selectedSegment ? <><h3 className="mt-2 text-xl font-black text-slate-900">{selectedSegment.name}</h3><p className="mt-1 text-sm text-slate-600">{selectedSegment.values}</p><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold">Requisito UX</dt><dd>{selectedSegment.uxRequirement}</dd></div><div><dt className="font-bold">Funcionalidad clave</dt><dd>{selectedSegment.keyFeature}</dd></div><div><dt className="font-bold">Tono del sistema</dt><dd>{selectedSegment.systemTone}</dd></div></dl></> : <p className="mt-2 text-sm">Añade un segmento para ver su salida UX.</p>}</aside></div><div className="mt-2 flex flex-wrap gap-2">{chartData.map((item) => <button key={item.id} onClick={() => setActiveSegmentId(item.id)} className={`rounded-full border px-3 py-1 text-sm font-semibold ${item.id === selectedSegment?.id ? 'border-teal-700 bg-teal-700 text-white' : 'border-slate-300 bg-white text-slate-700'}`}>{item.name}: {item.quota}%</button>)}</div></Panel>
        <div className="grid gap-6 lg:grid-cols-2"><Panel title={editingSegment ? `Editar ${editingSegment.name}` : 'Definir segmento'}><form className="space-y-3" onSubmit={segmentForm.handleSubmit(saveSegment)} noValidate><Field label="Nombre *" error={segmentForm.formState.errors.name?.message}><input className="field" {...segmentForm.register('name')} /></Field><Field label="Valores asociados *" error={segmentForm.formState.errors.values?.message}><input className="field" placeholder="seguridad, pragmatismo" {...segmentForm.register('values')} /></Field><Field label="Requisito UX derivado *" error={segmentForm.formState.errors.uxRequirement?.message}><textarea className="field" {...segmentForm.register('uxRequirement')} /></Field><Field label="Funcionalidad clave *" error={segmentForm.formState.errors.keyFeature?.message}><input className="field" {...segmentForm.register('keyFeature')} /></Field><Field label="Tono de sistema *" error={segmentForm.formState.errors.systemTone?.message}><input className="field" {...segmentForm.register('systemTone')} /></Field><button className="btn-primary">{editingSegment ? 'Actualizar segmento' : 'Añadir segmento'}</button>{editingSegment && <button type="button" className="btn-secondary ml-2" onClick={() => setEditingSegment(null)}>Cancelar</button>}</form><div className="mt-5 space-y-2">{active.segments.map((segment) => <div className="flex items-center justify-between rounded-lg border border-slate-200 p-2 text-sm" key={segment.id}><button className="font-semibold hover:underline" onClick={() => setActiveSegmentId(segment.id)}>{segment.name}</button><span className="flex gap-2"><button onClick={() => setEditingSegment(segment)} aria-label={`Editar ${segment.name}`}><Pencil size={15} /></button><button onClick={() => void deleteSegment(segment.id)} className="text-rose-700" aria-label={`Eliminar ${segment.name}`}><Trash2 size={15} /></button></span></div>)}</div></Panel>
          <Panel title={editingAssignment ? 'Editar asignación' : 'Asignar participante'} subtitle="Una persona puede pertenecer a más de un segmento si lo justificas con evidencia."><form className="space-y-3" onSubmit={assignmentForm.handleSubmit(saveAssignment)} noValidate><Field label="Usuario entrevistado *" error={assignmentForm.formState.errors.userId?.message}><select className="field" {...assignmentForm.register('userId')}><option value="">Selecciona…</option>{users.records.map((user) => <option value={user.id} key={user.id}>{user.alias}</option>)}</select></Field><fieldset><legend className="label">Segmentos *{assignmentForm.formState.errors.segmentIds?.message && <span className="error">{assignmentForm.formState.errors.segmentIds.message}</span>}</legend><div className="mt-2 grid grid-cols-2 gap-2">{active.segments.map((segment) => <label className="flex items-center gap-2 rounded-lg border border-slate-200 p-2 text-sm" key={segment.id}><input type="checkbox" value={segment.id} className="size-4 accent-teal-700" {...assignmentForm.register('segmentIds')} />{segment.name}</label>)}</div></fieldset><Field label="Evidencia *" error={assignmentForm.formState.errors.evidence?.message}><textarea className="field" placeholder="Comportamiento o cita que fundamenta la asignación" {...assignmentForm.register('evidence')} /></Field><button className="btn-primary"><Plus size={16} /> {editingAssignment ? 'Guardar asignación' : 'Asignar'}</button>{editingAssignment && <button type="button" className="btn-secondary ml-2" onClick={() => setEditingAssignment(null)}>Cancelar</button>}</form><div className="mt-5 space-y-2">{active.assignments.length === 0 ? <EmptyState>Asigna entrevistados para alimentar la rueda.</EmptyState> : active.assignments.map((assignment) => <div className="rounded-lg border border-slate-200 p-3 text-sm" key={assignment.id}><div className="flex justify-between gap-2"><strong>{users.records.find((user) => user.id === assignment.userId)?.alias ?? assignment.alias}</strong><span className="flex gap-2"><button onClick={() => setEditingAssignment(assignment)} aria-label="Editar asignación"><Pencil size={15} /></button><button onClick={() => void deleteAssignment(assignment.id)} className="text-rose-700" aria-label="Eliminar asignación"><Trash2 size={15} /></button></span></div><p className="mt-1 text-slate-600">{assignment.segmentIds.map((id) => active.segments.find((segment) => segment.id === id)?.name).filter(Boolean).join(' · ')}</p><p className="mt-1 text-xs text-slate-500">{assignment.evidence}</p></div>)}</div></Panel></div>
      </div> : <Panel title="Rueda pendiente"><EmptyState>Crea o selecciona una configuración para definir segmentos y asignar usuarios.</EmptyState></Panel>}</div>
    <ConfirmDialog open={Boolean(pendingDelete)} message={`Se eliminará “${pendingDelete?.title ?? ''}” y todas sus asignaciones.`} onCancel={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) void destroy(pendingDelete.id); if (active?.id === pendingDelete?.id) setActive(null); setPendingDelete(null) }} />
  </div>
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="label">{label}{children}{error && <span className="error">{error}</span>}</label> }
