import { useEffect, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowRight, Lightbulb, Pencil, Plus, Trash2 } from 'lucide-react'
import { z } from 'zod'
import { ConfirmDialog } from '../../components/ConfirmDialog'
import { ExportButtons } from '../../components/ExportButtons'
import { EmptyState, Panel } from '../../components/Panel'
import { useRecords } from '../../hooks/useRecords'
import { makeId, timestamp } from '../../lib/db'
import type { EmpathyFragment, EmpathyMap, Insight, InsightType, Quadrant } from '../../types/research'

const mapSchema = z.object({ subject: z.string().min(2, 'Indica la persona o segmento del mapa.') })
const fragmentSchema = z.object({ text: z.string().min(3, 'Escribe un fragmento de observación.'), quadrant: z.enum(['inbox', 'dice', 'hace', 'piensa', 'siente']), emotionalIntensity: z.coerce.number().min(1).max(10).optional() })
const insightSchema = z.object({ type: z.enum(['usabilidad', 'necesidad oculta', 'carga cognitiva', 'adaptación manual', 'innovación potencial']), description: z.string().min(8, 'Describe el insight con evidencia.'), priority: z.coerce.number().int().min(1).max(10) })
type MapForm = z.infer<typeof mapSchema>; type FragmentForm = z.infer<typeof fragmentSchema>; type InsightForm = z.infer<typeof insightSchema>
const quadrants: { id: Quadrant; title: string; description: string; color: string }[] = [
  { id: 'dice', title: 'Dice', description: 'Citas y expresiones literales.', color: 'border-sky-300 bg-sky-50' }, { id: 'hace', title: 'Hace', description: 'Comportamientos observables.', color: 'border-emerald-300 bg-emerald-50' }, { id: 'piensa', title: 'Piensa', description: 'Modelos mentales inferidos.', color: 'border-violet-300 bg-violet-50' }, { id: 'siente', title: 'Siente', description: 'Respuesta emocional e intensidad.', color: 'border-rose-300 bg-rose-50' },
]

export function EmpathyView() {
  const { records, loading, upsert, destroy } = useRecords<EmpathyMap>('empathyMaps')
  const [active, setActive] = useState<EmpathyMap | null>(null)
  const selectedInitialMap = useRef(false)
  const [pendingDelete, setPendingDelete] = useState<EmpathyMap | null>(null)
  const mapForm = useForm<MapForm>({ resolver: zodResolver(mapSchema), defaultValues: { subject: '' } })
  const fragmentForm = useForm<FragmentForm>({ resolver: zodResolver(fragmentSchema), defaultValues: { text: '', quadrant: 'inbox', emotionalIntensity: 5 } })
  const insightForm = useForm<InsightForm>({ resolver: zodResolver(insightSchema), defaultValues: { type: 'necesidad oculta', description: '', priority: 5 } })
  useEffect(() => { if (!selectedInitialMap.current && records.length > 0) { selectedInitialMap.current = true; setActive(records[0]) } }, [records])
  useEffect(() => { mapForm.reset({ subject: active?.subject ?? '' }) }, [active, mapForm])
  const saveMap = async (values: MapForm) => {
    const saved = await upsert({ id: active?.id ?? makeId('empathy'), createdAt: active?.createdAt ?? timestamp(), updatedAt: timestamp(), subject: values.subject, fragments: active?.fragments ?? [], insights: active?.insights ?? [] })
    setActive(saved)
  }
  const updateActive = async (patch: Partial<EmpathyMap>) => {
    if (!active) return
    const saved = await upsert({ ...active, ...patch, updatedAt: timestamp() }); setActive(saved)
  }
  const addFragment = async (values: FragmentForm) => {
    if (!active) return
    const fragment: EmpathyFragment = { id: makeId('fragment'), text: values.text, quadrant: values.quadrant, emotionalIntensity: values.quadrant === 'siente' ? values.emotionalIntensity : undefined }
    await updateActive({ fragments: [...active.fragments, fragment] }); fragmentForm.reset({ text: '', quadrant: 'inbox', emotionalIntensity: 5 })
  }
  const moveFragment = async (id: string, quadrant: Quadrant) => { if (!active) return; await updateActive({ fragments: active.fragments.map((item) => item.id === id ? { ...item, quadrant, emotionalIntensity: quadrant === 'siente' ? item.emotionalIntensity ?? 5 : undefined } : item) }) }
  const deleteFragment = async (id: string) => { if (active) await updateActive({ fragments: active.fragments.filter((item) => item.id !== id) }) }
  const addInsight = async (values: InsightForm) => { if (!active) return; const insight: Insight = { id: makeId('insight'), ...values }; await updateActive({ insights: [...active.insights, insight] }); insightForm.reset({ type: 'necesidad oculta', description: '', priority: 5 }) }
  const deleteInsight = async (id: string) => { if (active) await updateActive({ insights: active.insights.filter((item) => item.id !== id) }) }
  const inbox = active?.fragments.filter((item) => item.quadrant === 'inbox') ?? []
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Método 4</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Empathy Map · The Parser</h1><p className="mt-2 max-w-3xl text-slate-600">Procesa el ruido cualitativo sin borrar su origen: clasifica fragmentos por click en una cuadrícula 2×2 y conviértelos en insights priorizados.</p></header>
    <div className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Panel title={active ? 'Mapa seleccionado' : 'Crear un mapa'} subtitle="Cada mapa es un registro editable y exportable."><form onSubmit={mapForm.handleSubmit(saveMap)} className="space-y-3" noValidate><Field label="Sujeto del mapa *" error={mapForm.formState.errors.subject?.message}><input className="field" placeholder="p. ej., Dani - usuario extremo" {...mapForm.register('subject')} /></Field><button className="btn-primary">{active ? 'Guardar sujeto' : 'Crear mapa'}</button>{active && <button type="button" className="btn-secondary ml-2" onClick={() => setActive(null)}>Nuevo mapa</button>}</form><div className="mt-6 border-t border-slate-200 pt-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">Mapas guardados</h3><ExportButtons label="moderai-empathy-maps" records={records as unknown as Record<string, unknown>[]} /></div>{loading ? <p className="text-sm text-slate-500">Cargando…</p> : records.length === 0 ? <EmptyState>Crea un mapa para empezar a clasificar evidencia.</EmptyState> : <div className="space-y-2">{records.map((map) => <div key={map.id} className={`rounded-lg border p-3 ${active?.id === map.id ? 'border-teal-600 bg-teal-50' : 'border-slate-200'}`}><button className="w-full text-left" onClick={() => setActive(map)}><strong className="block text-sm">{map.subject}</strong><span className="text-xs text-slate-600">{map.fragments.length} fragmentos · {map.insights.length} insights</span></button><div className="mt-2 flex gap-1"><button className="btn-secondary !px-2 !py-1" onClick={() => setActive(map)} aria-label={`Editar ${map.subject}`}><Pencil size={14} /></button><button className="btn-secondary !px-2 !py-1 text-rose-700" onClick={() => setPendingDelete(map)} aria-label={`Eliminar ${map.subject}`}><Trash2 size={14} /></button></div></div>)}</div>}</div></Panel>
      {active ? <div className="space-y-6"><Panel title="Bandeja de ruido cualitativo" subtitle="Añade frases o comportamientos antes de interpretarlos."><form className="grid gap-3 md:grid-cols-[1fr_180px_110px_auto]" onSubmit={fragmentForm.handleSubmit(addFragment)} noValidate><Field label="Fragmento *" error={fragmentForm.formState.errors.text?.message}><input className="field" placeholder="Cita, observación o gesto" {...fragmentForm.register('text')} /></Field><Field label="Destino inicial"><select className="field" {...fragmentForm.register('quadrant')}><option value="inbox">Bandeja sin procesar</option>{quadrants.map((q) => <option value={q.id} key={q.id}>{q.title}</option>)}</select></Field><Field label="Intensidad 1-10"><input type="number" min="1" max="10" className="field" disabled={fragmentForm.watch('quadrant') !== 'siente'} {...fragmentForm.register('emotionalIntensity', { valueAsNumber: true })} /></Field><button className="btn-primary self-end"><Plus size={16} /> Añadir</button></form>{inbox.length > 0 && <div className="mt-4 rounded-xl border border-dashed border-amber-300 bg-amber-50 p-3"><h3 className="font-bold text-amber-950">Sin procesar · asigna por click</h3><div className="mt-3 space-y-2">{inbox.map((fragment) => <div className="rounded-lg bg-white p-3 shadow-sm" key={fragment.id}><p className="text-sm text-slate-800">{fragment.text}</p><div className="mt-2 flex flex-wrap gap-1">{quadrants.map((q) => <button className="btn-secondary !px-2 !py-1 text-xs" key={q.id} onClick={() => void moveFragment(fragment.id, q.id)}>{q.title} <ArrowRight size={12} /></button>)}<button className="btn-secondary !px-2 !py-1 text-rose-700" onClick={() => void deleteFragment(fragment.id)} aria-label="Eliminar fragmento"><Trash2 size={13} /></button></div></div>)}</div></div>}</Panel>
        <Panel title="Cuadrícula de empatía 2×2" subtitle="Los fragmentos se distribuyen de verdad; puedes reasignarlos por click desde la bandeja."><div className="grid gap-3 md:grid-cols-2">{quadrants.map((quadrant) => <section className={`min-h-52 rounded-xl border-2 p-4 ${quadrant.color}`} key={quadrant.id} aria-label={`Cuadrante ${quadrant.title}`}><h3 className="text-lg font-black text-slate-900">{quadrant.title}</h3><p className="mt-1 text-xs text-slate-600">{quadrant.description}</p><div className="mt-3 space-y-2">{active.fragments.filter((item) => item.quadrant === quadrant.id).length === 0 ? <p className="text-sm italic text-slate-500">Aún sin fragmentos</p> : active.fragments.filter((item) => item.quadrant === quadrant.id).map((fragment) => <article className="rounded-lg bg-white p-3 text-sm shadow-sm" key={fragment.id}><p>{fragment.text}</p>{quadrant.id === 'siente' && <span className="mt-2 inline-block rounded-full bg-rose-100 px-2 py-0.5 text-xs font-bold text-rose-800">Intensidad {fragment.emotionalIntensity ?? 5}/10</span>}<div className="mt-2 flex justify-end"><button className="text-xs font-semibold text-rose-700 hover:underline" onClick={() => void deleteFragment(fragment.id)}>Quitar</button></div></article>)}</div></section>)}</div></Panel>
        <Panel title="Generador de insights" subtitle="Estos insights se enlazan de forma automática en Mapeo de Requerimientos." actions={<ExportButtons label="moderai-empathy-insights" records={active.insights as unknown as Record<string, unknown>[]} />}><form className="grid gap-3 md:grid-cols-[175px_1fr_100px_auto]" onSubmit={insightForm.handleSubmit(addInsight)} noValidate><Field label="Tipo"><select className="field" {...insightForm.register('type')}>{(['usabilidad', 'necesidad oculta', 'carga cognitiva', 'adaptación manual', 'innovación potencial'] as InsightType[]).map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Insight *" error={insightForm.formState.errors.description?.message}><input className="field" placeholder="Hallazgo interpretable y accionable" {...insightForm.register('description')} /></Field><Field label="Prioridad 1-10"><input type="number" min="1" max="10" className="field" {...insightForm.register('priority', { valueAsNumber: true })} /></Field><button className="btn-primary self-end"><Lightbulb size={16} /> Crear</button></form><div className="mt-4 space-y-2">{active.insights.length === 0 ? <EmptyState>Aún no hay insights estructurados.</EmptyState> : active.insights.map((insight) => <div className="flex items-start justify-between gap-3 rounded-xl border border-slate-200 p-3" key={insight.id}><div><span className="tag">{insight.type}</span><p className="mt-2 text-sm text-slate-700">{insight.description}</p></div><div className="flex items-center gap-3"><span className="text-sm font-bold">P{insight.priority}</span><button className="text-rose-700" onClick={() => void deleteInsight(insight.id)} aria-label="Eliminar insight"><Trash2 size={16} /></button></div></div>)}</div></Panel>
      </div> : <Panel title="Selecciona o crea un mapa"><EmptyState>Una vez creado, podrás procesar fragmentos y ver aquí la cuadrícula interactiva.</EmptyState></Panel>}</div>
    <ConfirmDialog open={Boolean(pendingDelete)} message={`Se eliminará el mapa de ${pendingDelete?.subject ?? ''}, incluidos sus fragmentos e insights.`} onCancel={() => setPendingDelete(null)} onConfirm={() => { if (pendingDelete) void destroy(pendingDelete.id); if (active?.id === pendingDelete?.id) setActive(null); setPendingDelete(null) }} />
  </div>
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="label">{label}{children}{error && <span className="error">{error}</span>}</label> }
